version: '3.8'

services:
  snowflake-connector-agent:
    image: snowflakedb/database-connector-agent:latest
    container_name: snowflake-connector-agent
    restart: unless-stopped
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - CONNECTOR_CONFIG_PATH=/etc/snowflake-connector/config.yaml
    volumes:
      - ./config:/etc/snowflake-connector
    ports:
      - "8080:8080"
    networks:
      - snowflake-network

networks:
  snowflake-network:
    driver: bridge 